version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: my_app_db
      DB_USERNAME: my_app_user
      DB_PASSWORD: my_app_password
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: taskmanager-db
    image: mysql:8.0
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: my_app_db
      MYSQL_USER: my_app_user
      MYSQL_PASSWORD: my_app_password
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql 
    networks:
      - app-network

volumes:
  db_data: 

networks:
  app-network:
    driver: bridge
